#!/bin/bash

declare -r in_doc="${1}"
declare -r out_png="${2}"

declare -r intermediateFile_2png="/$(basename "${1%.*}".png)"
declare -r fileExt="${1##*.}"

declare -r size="${3}x${3}"

declare -A colors
colors["odt"]='#328ABD'
colors["ods"]='#4EA33F'
colors["odp"]='#C16A3C'
colors["odg"]='#D98E49'
colors["doc"]='#6597DF'
colors["docx"]='#407DD4'
colors["docm"]='#407DD4'
colors["xls"]='#3BA67A'
colors["xlsx"]='#19895A'
colors["xlsm"]='#19895A'
colors["ppt"]='#DB5A3C'
colors["pptx"]='#DB5A3C'

colors["pps"]='#DB5A3C'
colors["ppsx"]='#DB5A3C'
colors["pptm"]='#DB5A3C'

colors["rtf"]='#F04D45'
colors["txt"]='#F19B36'
colors["fodt"]='#3BC5F4'
colors["fods"]='#76A052'
colors["fodg"]='#B351BC'
colors["csv"]='#A7D183'
colors["pdf"]='#F05A6C'
colors["fodp"]='#FFBA80'

case "${fileExt,,}" in
    odt | ods | odp | odg | doc | docx | docm | xls | xlsx | xlsm | ppt | pptx | rtf | txt | fodt | csv | fods | fodg | fodp | pps | ppsx | pptm)
        if ! timeout 5s soffice  --headless \
                --invisible \
                --nocrashreport \
                --nodefault \
                --nofirststartwizard \
                --nologo \
                --norestore \
                -env:UserInstallation=file:///temp \
                --convert-to png "${in_doc}"
        then
            exit 1
        fi
    ;;
    pdf )
        if ! timeout 5s convert -density 300 "${in_doc}[0]" -background white -flatten "png:${intermediateFile_2png}"
        then
            exit 1
        fi
    ;;
    *)
        exit 1
    ;;
esac



# @fixme: не происходит наложение иконки для документов на гугл-диске

convert "${intermediateFile_2png}" -thumbnail "${size}" \
    \( +clone -fill "rgba(0,0,0,0.2)" -draw "polygon 0,0 106,0 0,69" \) \
    \( +clone -fill "${colors[${fileExt,,}]}" -draw "polygon 0,0 103,0 0,64"  +repage \) \
    -background none -layers flatten +repage \
    -gravity northwest -pointsize 16 -fill white -annotate +10+10 "${fileExt^^}" \
    "png:${out_png}"



[[ -f "${intermediateFile_2png}" ]] && rm -f "${intermediateFile_2png}"

