#!/bin/bash

out_png="${2}"

intermediateFile_2png="/$(basename "${1%.*}".png)"
fileType="${1##*.}"

iconsSet='/usr/share/icons/Yaru'
opacity='0.65'
geometry='+3+8'
gravity='SouthEast'

if ! timeout 5s soffice  --headless \
         --invisible \
         --nocrashreport \
         --nodefault \
         --nofirststartwizard \
         --nologo \
         --norestore \
         -env:UserInstallation=file:///temp \
         --convert-to png "${1}"
then
    exit 1
fi


convert "${intermediateFile_2png}" -thumbnail "${3}x${3}" "png:${2}"

iconize() {
    convert "${iconsSet}/32x32@2x/mimetypes/${1}" -alpha on -channel A -evaluate multiply "${opacity}" +channel png:- | composite -gravity $gravity -geometry $geometry - "${out_png}" "${out_png}"
}


if [[ -d "${iconsSet}" ]]
then
    case "${fileType}" in
     odt)
        iconize 'application-vnd.oasis.opendocument.text.png'
        ;;
    ods)
        iconize 'application-vnd.oasis.opendocument.spreadsheet.png'
        ;;
    odp)
        iconize 'application-vnd.oasis.opendocument.presentation.png'
        ;;
    odg)
        iconize 'application-vnd.oasis.opendocument.graphics.png'
        ;;
    doc)
        iconize 'application-vnd.ms-word.png'
        ;;
    docx)
        iconize 'application-vnd.openxmlformats-officedocument.wordprocessingml.document.png'
        ;;
    xls)
        iconize 'application-vnd.ms-excel.png'
        ;;
    xlsx)
        iconize 'application-vnd.openxmlformats-officedocument.spreadsheetml.sheet.png'
        ;;
    ppt)
        iconize 'application-vnd.ms-powerpoint.png'
        ;;
    pptx)
        iconize 'application-vnd.openxmlformats-officedocument.presentationml.slideshow.png'
        ;;
     *)
        iconize 'text-document.png'
        ;;
    esac

fi

[[ -f "${1}" ]] && rm -f "${1}"
[[ -f "${intermediateFile_2png}" ]] && rm -f "${intermediateFile_2png}"

